### PR TITLE
Update roadmap

### LINKED ISSUE #16: Update Roadmap for align goals with CZI Proposals
- [ ] Add "Better support of Open Geospatial data formats" (EOSS)
- [ ] Add "Better support for large streaming gridded data support" (EOSS)
- [ ] Improve contributor / end-user diversity (DEI)
- [ ] Better accessibility / sharing / data export (DEI...)

### PR DESCRIPTION
**Pull request by tcmetzger**
PR resolves #16. This is a first draft of the additional roadmap items.

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM

**Review by jbednar — APPROVED** [review]
Looks, good, thanks! I made some minor edits/additions.

**Comment by brainwane** [comment]
@bryevdv can we merge this? Thanks.

**Comment by bryevdv** [comment]
FYI I'm fine with an "I'll merge this tomorrow unless there are more comments" timebox, no need for me to be a bottleneck :)

**Pull request merged**
